### ISSUE TITLE
Python 3.11?

### ISSUE THREAD

**Issue by yfiua** [quantiacs-io/toolbox#4]
Python 3.7 reached end-of-life on June 27th, 2023 and is quite obsolete. It makes sense to upgrade to e.g. 3.11 for new features and better support.

**Comment by burdinskiy-quantnet** [comment]
Dear yfiua,

Thank you for reaching out and for your suggestion regarding the Python version upgrade.

We appreciate your attention to the end-of-life status of Python 3.7. As you rightly pointed out, upgrading to a newer version of Python is essential for accessing new features and ensuring better support.

In line with your suggestion, we have already upgraded our system to Python 3.10. This version provides a balance between newer features and stable performance, ensuring compatibility with our existing codebase and dependencies.

To install the necessary libraries with this updated Python version, you can refer to our README file or visit the documentation section at [Quantiacs Python Library Documentation](https://quantiacs.com/documentation/en/user_guide/local_development.html). These resources provide detailed instructions and guidance for a smooth installation process.

We are committed to continuously improving our platform and are grateful for your input. If you have any further questions or face any issues during the installation process, please do not hesitate to reach out.

Best regards
